spring:
  application:
    name: Inventory Service
    version: 1.0.0
    description: Order Service API
  datasource:
    url: jdbc:mysql://localhost:3309/inventory_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html