services:
  mongodb:
    image: mongo:8.0
    container_name: product_service_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
        - product_service_mongodb:/data/db

volumes:
  product_service_mongodb: