server:
  port: 8762

eureka:
  instance:
    hostname: eureka-server2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server1:8761/eureka/, http://eureka-server2:8762/eureka/