server:
    port: 8080

spring:
  application:
    name: product-service
    description: Product Service API
    version: 1.0.0

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/product-service?authSource=admin

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}
    metadataMap:
      zone: BR

  client:
    region: IN
    availability-zones:
      IN: BR,BLR
    service-url:
      BR: http://eureka-server1:8761/eureka/
      BLR: http://eureka-server2:8762/eureka/

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    httpexchanges:
      enabled: true

logging:
  level:
    com.upendra.product_service: debug