server:
    port: 8080

spring:
  application:
    name: product-service
    description: Product Service API
    version: 1.0.0

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/product-service?authSource=admin

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    httpexchanges:
      enabled: true

logging:
  level:
    com.upendra.product_service: debug