services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3308:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
    mysql:

