spring:
  application:
    name: Order Service
  datasource:
    url: jdbc:mysql://localhost:3308/order_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081