server:
  port: 8082

spring:
  application:
    name: Order Service API
    version: 1.0.0
    description: Order Service API
  datasource:
    url: jdbc:mysql://localhost:3308/order_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    openfeign:
        client:
          config:
            default:
              connectTimeout: 5000
              readTimeout: 5000
            inventory-service:
              url: http://localhost:8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html