spring:
  application:
    name: Order Service
  datasource:
    url: jdbc:mysql://localhost:3308/order_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    openfeign:
        client:
          config:
            default:
              connectTimeout: 5000
              readTimeout: 5000
            inventory-service:
              url: http://localhost:8082

server:
  port: 8081